# MCP Server Configuration
# Configuration for Model Context Protocol servers providing dental practice intelligence

mcp_servers:
  dental_quality_server:
    enabled: true
    url: "http://localhost:8001"
    timeout_seconds: 30
    health_check_interval: 300  # 5 minutes
    capabilities:
      - validate_patient_record_integrity
      - audit_dental_workflow_compliance
      - validate_hipaa_compliance
      - check_clinical_data_integrity
    
  model_generator_server:
    enabled: true
    url: "http://localhost:8002"
    timeout_seconds: 60
    health_check_interval: 600  # 10 minutes
    capabilities:
      - generate_staging_model
      - analyze_table_relationships
      - generate_model_documentation
      - suggest_dbt_tests
    
  orchestration_server:
    enabled: true
    url: "http://localhost:8003"
    timeout_seconds: 45
    health_check_interval: 300  # 5 minutes
    capabilities:
      - optimize_pipeline_schedule
      - monitor_pipeline_health
      - predict_performance_issues
      - manage_resource_allocation
    
  business_intelligence_server:
    enabled: true
    url: "http://localhost:8004"
    timeout_seconds: 90
    health_check_interval: 600  # 10 minutes
    capabilities:
      - analyze_practice_performance
      - generate_executive_dashboard
      - analyze_revenue_cycle_health
      - generate_health_recommendations

# Fallback configuration when MCP servers are unavailable
fallback_behavior:
  use_basic_health_checks: true
  log_mcp_failures: true
  continue_without_mcp: true
  show_fallback_warnings: true

# Health check thresholds
health_thresholds:
  technical_health:
    excellent: 95
    good: 85
    warning: 70
    critical: 50
  
  dental_health:
    excellent: 90
    good: 80
    warning: 65
    critical: 45
  
  overall_health:
    weights:
      technical: 0.4
      dental: 0.6

# Integration settings
integration:
  dbt_test_integration: true
  table_config_integration: true
  existing_health_checker_integration: true
  cli_enhancement: true
  powershell_integration: true

# Dental-specific validation rules
dental_validation:
  patient_data:
    required_fields: ["patient_id", "first_name", "last_name"]
    cross_table_validation: true
    orphan_record_detection: true
  
  clinical_workflows:
    appointment_procedure_alignment: true
    insurance_authorization_validation: true
    treatment_plan_compliance: true
  
  revenue_cycle:
    payment_allocation_validation: true
    insurance_claim_tracking: true
    ar_aging_analysis: true
  
  compliance:
    hipaa_phi_protection: true
    access_control_monitoring: true
    audit_trail_validation: true
    data_retention_compliance: true 