# Pipeline configuration for the dental clinic ETL pipeline

# General settings
general:
  pipeline_name: "dental_clinic_elt"
  environment: "production"
  timezone: "UTC"
  max_retries: 3
  retry_delay_seconds: 300
  batch_size: 1000
  parallel_jobs: 4

# Database connections
connections:
  source:
    type: "mysql"
    pool_size: 5
    pool_timeout: 30
    pool_recycle: 3600
    connect_timeout: 60
    read_timeout: 300
    write_timeout: 300

  staging:
    type: "mysql"
    pool_size: 5
    pool_timeout: 30
    pool_recycle: 3600
    connect_timeout: 60
    read_timeout: 300
    write_timeout: 300

  target:
    type: "postgresql"
    pool_size: 5
    pool_timeout: 30
    pool_recycle: 3600
    connect_timeout: 60
    read_timeout: 300
    write_timeout: 300

# Pipeline stages
stages:
  extract:
    enabled: true
    schedule: "*/15 * * * *"  # Every 15 minutes
    timeout_minutes: 30
    error_threshold: 0.01  # 1% error rate threshold
    validation:
      enabled: true
      sample_size: 1000
      rules:
        - name: "row_count_check"
          threshold: 0.99  # 99% match required
        - name: "null_check"
          threshold: 0.95  # 95% non-null required

  load:
    enabled: true
    schedule: "*/30 * * * *"  # Every 30 minutes
    timeout_minutes: 45
    error_threshold: 0.01
    validation:
      enabled: true
      sample_size: 1000
      rules:
        - name: "data_type_check"
          threshold: 1.0  # 100% match required
        - name: "constraint_check"
          threshold: 1.0

  transform:
    enabled: true
    schedule: "0 * * * *"  # Every hour
    timeout_minutes: 60
    error_threshold: 0.01
    validation:
      enabled: true
      sample_size: 1000
      rules:
        - name: "business_rule_check"
          threshold: 1.0
        - name: "calculation_check"
          threshold: 0.99

# Monitoring and alerting
monitoring:
  metrics:
    collection_interval: 60  # seconds
    retention_days: 30
    storage_path: "metrics/"

  alerts:
    slack:
      enabled: true
      channel: "#dental-clinic-alerts"
      severity_levels:
        - error
        - warning
        - info

    email:
      enabled: true
      recipients:
        - "data-team@dentalclinic.com"
        - "oncall@dentalclinic.com"
      severity_levels:
        - error
        - warning

# Performance settings
performance:
  memory_limit_mb: 4096
  cpu_limit_percent: 80
  io_limit_mbps: 100
  temp_storage_gb: 10

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file:
    enabled: true
    path: "logs/pipeline.log"
    max_size_mb: 100
    backup_count: 10
  console:
    enabled: true
    level: "INFO"

# Data retention
retention:
  staging:
    days: 7
    cleanup_schedule: "0 0 * * *"  # Daily at midnight
  target:
    days: 365
    cleanup_schedule: "0 0 1 * *"  # Monthly on the 1st

# Error handling
error_handling:
  max_consecutive_failures: 3
  failure_notification_threshold: 2
  auto_retry:
    enabled: true
    max_attempts: 3
    delay_minutes: 5
  error_logging:
    enabled: true
    path: "logs/errors.log"
    max_size_mb: 100
    backup_count: 10

# Security settings
security:
  encryption:
    enabled: true
    algorithm: "AES-256"
  ssl:
    enabled: true
    verify: true
  authentication:
    method: "token"
    token_expiry_hours: 24 