# PowerShell script to set up API key for frontend development
# This reads the API key from .ssh/dbt-dental-clinic-api-key.pem and creates/updates .env file

$projectRoot = Split-Path -Parent $PSScriptRoot
$pemFile = Join-Path $projectRoot ".ssh" "dbt-dental-clinic-api-key.pem"
$envFile = Join-Path $PSScriptRoot ".env"

Write-Host "Setting up frontend API key..." -ForegroundColor Cyan
Write-Host "Looking for API key at: $pemFile" -ForegroundColor Gray

if (-not (Test-Path $pemFile)) {
    Write-Host "❌ API key file not found at: $pemFile" -ForegroundColor Red
    Write-Host "Please ensure the API key file exists." -ForegroundColor Yellow
    exit 1
}

try {
    # Read API key from PEM file
    $keyContent = Get-Content $pemFile -Raw
    $lines = $keyContent -split "`n"
    $keyLines = $lines | Where-Object { 
        $_ -and 
        -not $_.StartsWith('-----BEGIN') -and 
        -not $_.StartsWith('-----END') 
    }
    $apiKey = ($keyLines | ForEach-Object { $_.Trim() }) -join ''
    
    if (-not $apiKey) {
        Write-Host "❌ Could not extract API key from PEM file" -ForegroundColor Red
        exit 1
    }
    
    Write-Host "✅ API key extracted successfully" -ForegroundColor Green
    
    # Create or update .env file
    $envContent = @"
# Frontend Environment Variables
# Auto-generated by setup_api_key.ps1

# API Configuration
VITE_API_URL=http://localhost:8000

# API Key - Loaded from .ssh/dbt-dental-clinic-api-key.pem
VITE_API_KEY=$apiKey
"@
    
    Set-Content -Path $envFile -Value $envContent -Force
    Write-Host "✅ Created/updated .env file at: $envFile" -ForegroundColor Green
    Write-Host ""
    Write-Host "⚠️  IMPORTANT: Restart your frontend dev server for changes to take effect!" -ForegroundColor Yellow
    Write-Host "   Stop the server (Ctrl+C) and run: npm run dev" -ForegroundColor Yellow
    
} catch {
    Write-Host "❌ Error: $_" -ForegroundColor Red
    exit 1
}

