-- =============================================================================
-- Snowflake bootstrap — run in Snowsight (Worksheets) while logged in
-- Role: ACCOUNTADMIN (or a role that can create warehouses/databases/roles)
--
-- Tip: Highlight ONE statement (through its trailing semicolon), then Run.
--      Do not paste/run the entire file in one shot if you get:
--      "Multiple SQL statements in a single API call are not supported"
-- =============================================================================

-- 1) Cost guardrails
CREATE RESOURCE MONITOR IF NOT EXISTS RM_DEMO_CREDITS
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 50 PERCENT DO NOTIFY
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

-- 2) Warehouse (X-Small, auto-suspend 60s)
CREATE WAREHOUSE IF NOT EXISTS WH_DEMO_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Portfolio demo warehouse - payments/collections mini stack';

ALTER WAREHOUSE WH_DEMO_XS SET RESOURCE_MONITOR = RM_DEMO_CREDITS;

-- 3) Database + schemas
CREATE DATABASE IF NOT EXISTS OPENDENTAL_SF
  COMMENT = 'Snowflake portfolio mini warehouse - synthetic only - not Postgres opendental_analytics';

CREATE SCHEMA IF NOT EXISTS OPENDENTAL_SF.RAW
  COMMENT = 'Demo Postgres export landing zone';

CREATE SCHEMA IF NOT EXISTS OPENDENTAL_SF.STAGING;

CREATE SCHEMA IF NOT EXISTS OPENDENTAL_SF.INT;

CREATE SCHEMA IF NOT EXISTS OPENDENTAL_SF.MARTS;

CREATE SCHEMA IF NOT EXISTS OPENDENTAL_SF.DBT
  COMMENT = 'Default dbt target.schema placeholder';

CREATE STAGE IF NOT EXISTS OPENDENTAL_SF.RAW.DEMO_EXPORT
  COMMENT = 'Internal stage for demo Postgres CSV exports';

-- 4) Roles
CREATE ROLE IF NOT EXISTS TRANSFORMER
  COMMENT = 'dbt runs and COPY INTO RAW';

CREATE ROLE IF NOT EXISTS ANALYST
  COMMENT = 'Read marts for portfolio demos';

-- 5) Grants — warehouse / database
GRANT USAGE ON WAREHOUSE WH_DEMO_XS TO ROLE TRANSFORMER;
GRANT USAGE ON WAREHOUSE WH_DEMO_XS TO ROLE ANALYST;
GRANT USAGE ON DATABASE OPENDENTAL_SF TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE OPENDENTAL_SF TO ROLE ANALYST;

-- 6) Grants — schemas
GRANT USAGE ON ALL SCHEMAS IN DATABASE OPENDENTAL_SF TO ROLE TRANSFORMER;
GRANT USAGE ON SCHEMA OPENDENTAL_SF.MARTS TO ROLE ANALYST;
GRANT USAGE ON SCHEMA OPENDENTAL_SF.STAGING TO ROLE ANALYST;
GRANT USAGE ON SCHEMA OPENDENTAL_SF.INT TO ROLE ANALYST;

GRANT ALL ON SCHEMA OPENDENTAL_SF.RAW TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA OPENDENTAL_SF.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA OPENDENTAL_SF.INT TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA OPENDENTAL_SF.MARTS TO ROLE TRANSFORMER;
GRANT ALL ON SCHEMA OPENDENTAL_SF.DBT TO ROLE TRANSFORMER;

-- 7) Grants — existing + future objects
GRANT ALL ON ALL TABLES IN SCHEMA OPENDENTAL_SF.RAW TO ROLE TRANSFORMER;
GRANT ALL ON ALL VIEWS IN SCHEMA OPENDENTAL_SF.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA OPENDENTAL_SF.INT TO ROLE TRANSFORMER;
GRANT ALL ON ALL TABLES IN SCHEMA OPENDENTAL_SF.MARTS TO ROLE TRANSFORMER;

GRANT SELECT ON ALL TABLES IN SCHEMA OPENDENTAL_SF.MARTS TO ROLE ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA OPENDENTAL_SF.STAGING TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA OPENDENTAL_SF.INT TO ROLE ANALYST;

GRANT ALL ON FUTURE TABLES IN SCHEMA OPENDENTAL_SF.RAW TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE VIEWS IN SCHEMA OPENDENTAL_SF.STAGING TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA OPENDENTAL_SF.INT TO ROLE TRANSFORMER;
GRANT ALL ON FUTURE TABLES IN SCHEMA OPENDENTAL_SF.MARTS TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA OPENDENTAL_SF.MARTS TO ROLE ANALYST;

GRANT READ, WRITE ON STAGE OPENDENTAL_SF.RAW.DEMO_EXPORT TO ROLE TRANSFORMER;

-- 8) Attach roles to your login user
GRANT ROLE TRANSFORMER TO USER CONCRETE1866;
GRANT ROLE ANALYST TO USER CONCRETE1866;
ALTER USER CONCRETE1866 SET DEFAULT_ROLE = TRANSFORMER;
ALTER USER CONCRETE1866 SET DEFAULT_WAREHOUSE = WH_DEMO_XS;

-- 9) Optional convenience
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;
GRANT ROLE ANALYST TO ROLE SYSADMIN;

-- 10) Sanity check (optional)
SHOW DATABASES LIKE 'OPENDENTAL_SF';
SHOW WAREHOUSES LIKE 'WH_DEMO_XS';
SHOW ROLES LIKE 'TRANSFORMER';
