# yaml-language-server: $schema=https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/dbt_project.json
name: 'dbt_dental_models'
version: '1.0.0'
config-version: 2

# Make sure this matches exactly what's in your profiles.yml
profile: 'dbt_dental_models'

# Configure quote policy for case-sensitive identifiers
quoting:
  database: true
  schema: true
  identifier: true

# Paths configuration
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
docs-paths: ["dbt_docs"]

# Build artifacts location (using default target directory)
clean-targets:
    - "target"
    - "dbt_packages"

# Variables configuration
vars:
  max_valid_date: current_date
  schedule_window_days: 30

# Hooks for ETL tracking (run-level only for now)
on-run-start:
  - "{{ log('Starting dbt transformation run', info=true) }}"
  - "{{ update_etl_transform_status('started') }}"

on-run-end:
  - "{{ log('Completed dbt transformation run', info=true) }}"
  - "{{ update_etl_transform_status('completed') }}"

# Database/schema configuration
models:
  dbt_dental_models  :
    # Enable tests now that we've fixed the case sensitivity issue
    +tests:
      +enabled: true
    
    # Configure materializations by folder
    staging:
      +materialized: view  # Default materialization, some models override this to be tables
      +schema: staging
      +description: "Staging models for raw data transformation"
    
    intermediate:
      +materialized: table
      +schema: intermediate
      +description: "Intermediate models for business logic implementation"
    
    marts:
      +materialized: table
      +schema: marts
      +description: "Mart models for business reporting and analytics"

# Package dependencies - temporarily disabled for debugging
packages:
  - package: dbt-labs/dbt_utils
    version: 1.3.0
  - package: metaplane/dbt_expectations
    version: 0.10.8
  - package: godatadriven/dbt_date
    version: 0.13.0
  - package: dbt-labs/audit_helper
    version: 0.12.1