tables:
  patient:
    incremental_column: DateModified
    batch_size: 1000
    extraction_strategy: incremental
    table_importance: critical
    estimated_size_mb: 500
    estimated_rows: 100000
  appointment:
    incremental_column: DateModified
    batch_size: 500
    extraction_strategy: incremental
    table_importance: important
    estimated_size_mb: 200
    estimated_rows: 50000 