# =========== CORE CONFIGURATION TABLES ===========
version: 2

sources:
  - name: opendental
    description: "OpenDental data in PostgreSQL"
    database: opendental_analytics
    schema: raw  # Raw data from ETL pipeline
    tables:
      - name: clinic
        description: >
          Core clinic/location information for multi-location practices.
          Contains essential configuration for each clinic location including
          contact information, billing details, provider assignments, and
          operational settings.
        columns:
          - name: "ClinicNum"
            description: "Primary key for clinic records"
            tests:
              - unique
              - not_null
          - name: "Description"
            description: "Name or description of the clinic location"
          - name: "Abbr"
            description: "Abbreviation used for the clinic in reports and displays"
          - name: "ItemOrder"
            description: "Display order for the clinic in lists and dropdowns"
          - name: "Address"
            description: "Primary address line of the clinic"
          - name: "Address2"
            description: "Secondary address line of the clinic"
          - name: "City"
            description: "City where the clinic is located"
          - name: "State"
            description: "State where the clinic is located"
          - name: "Zip"
            description: "ZIP/Postal code of the clinic"
          - name: "Phone"
            description: "Contact phone number for the clinic"
          - name: "Fax"
            description: "Fax number for the clinic"
          - name: "EmailAddressNum"
            description: "Foreign key to email address record"
          - name: "EmailAliasOverride"
            description: "Custom email alias for the clinic"
          - name: "BankNumber"
            description: "Bank account number for the clinic"
          - name: "BillingAddress"
            description: "Primary billing address line"
          - name: "BillingAddress2"
            description: "Secondary billing address line"
          - name: "BillingCity"
            description: "City for billing address"
          - name: "BillingState"
            description: "State for billing address"
          - name: "BillingZip"
            description: "ZIP/Postal code for billing address"
          - name: "PayToAddress"
            description: "Primary pay-to address line"
          - name: "PayToAddress2"
            description: "Secondary pay-to address line"
          - name: "PayToCity"
            description: "City for pay-to address"
          - name: "PayToState"
            description: "State for pay-to address"
          - name: "PayToZip"
            description: "ZIP/Postal code for pay-to address"
          - name: "DefaultProv"
            description: "Foreign key to default provider for the clinic"
          - name: "InsBillingProv"
            description: "Foreign key to insurance billing provider"
          - name: "DefaultPlaceService"
            description: "Default place of service code for the clinic"
          - name: "IsMedicalOnly"
            description: "Flag indicating if clinic is medical-only (0=no, 1=yes)"
          - name: "UseBillAddrOnClaims"
            description: "Flag to use billing address on insurance claims (0=no, 1=yes)"
          - name: "IsInsVerifyExcluded"
            description: "Flag to exclude from insurance verification (0=no, 1=yes)"
          - name: "IsConfirmEnabled"
            description: "Flag for appointment confirmation feature (0=no, 1=yes)"
          - name: "IsConfirmDefault"
            description: "Flag for default confirmation setting (0=no, 1=yes)"
          - name: "IsNewPatApptExcluded"
            description: "Flag to exclude from new patient appointments (0=no, 1=yes)"
          - name: "IsHidden"
            description: "Flag to hide clinic from normal view (0=no, 1=yes)"
          - name: "HasProcOnRx"
            description: "Flag for procedure on prescription feature (0=no, 1=yes)"
          - name: "Region"
            description: "Foreign key to region table"
          - name: "TimeZone"
            description: "Timezone setting for the clinic"
          - name: "SchedNote"
            description: "Scheduling notes for the clinic"
          - name: "MedLabAccountNum"
            description: "Medical lab account number"
          - name: "ExternalID"
            description: "External system identifier"
          - name: "SmsContractDate"
            description: "Date of SMS contract"
          - name: "SmsMonthlyLimit"
            description: "Monthly SMS message limit"
        meta:
          contains_pii: true
          business_owners: ["dental_operations_team"]
          technical_owners: ["data_engineering_team"]
          data_quality_results:
            last_tested: '2024-03-14'
            tests_passed: 15
            tests_total: 15 