#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Generate a secure API key for LOCAL DEVELOPMENT ONLY
    
.DESCRIPTION
    Generates a cryptographically secure random API key and stores it in
    .ssh/dbt-dental-clinic-api-key.pem with restricted permissions.
    
    ⚠️  WARNING: This is for LOCAL DEVELOPMENT ONLY.
    The production API key is stored in deployment_credentials.json as "api_key"
    and is used by the public portfolio site at https://dbtdentalclinic.com
    
    DO NOT use this script to generate production keys. Production keys are:
    - Managed on EC2 at /opt/dbt_dental_clinic/api/.env
    - Stored in deployment_credentials.json
    - Embedded in production frontend builds
    
.EXAMPLE
    .\generate_api_key.ps1
    
.EXAMPLE
    .\generate_api_key.ps1 -UpdateFrontend
#>

param(
    [Parameter(Mandatory=$false)]
    [switch]$UpdateFrontend
)

# Get project root (assumes script is in scripts/ directory)
$scriptDir = Split-Path $PSScriptRoot -Parent
$projectRoot = if ($scriptDir) { $scriptDir } else { Get-Location }

# API key file location
$sshDir = Join-Path $projectRoot ".ssh"
$apiKeyFile = Join-Path $sshDir "dbt-dental-clinic-api-key.pem"

Write-Host "`n🔐 Generating Secure API Key (LOCAL DEVELOPMENT ONLY)" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "⚠️  WARNING: This script generates keys for LOCAL DEVELOPMENT ONLY" -ForegroundColor Yellow
Write-Host "   Production API key is managed separately:" -ForegroundColor Yellow
Write-Host "   - Stored in: deployment_credentials.json (api_key)" -ForegroundColor Gray
Write-Host "   - Used by: https://api.dbtdentalclinic.com" -ForegroundColor Gray
Write-Host "   - Embedded in: Production frontend builds" -ForegroundColor Gray
Write-Host ""
$confirm = Read-Host "Continue with local development key generation? (y/N)"
if ($confirm -ne 'y' -and $confirm -ne 'Y') {
    Write-Host "Cancelled." -ForegroundColor Gray
    exit 0
}
Write-Host ""

# Create .ssh directory if it doesn't exist
if (-not (Test-Path $sshDir)) {
    Write-Host "📁 Creating .ssh directory..." -ForegroundColor Gray
    New-Item -ItemType Directory -Path $sshDir -Force | Out-Null
}

# Generate cryptographically secure random API key
# Using .NET System.Security.Cryptography for production-grade randomness
Write-Host "🔑 Generating cryptographically secure API key..." -ForegroundColor Gray

# Generate 32 bytes of random data (256 bits)
$bytes = New-Object byte[] 32
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$rng.GetBytes($bytes)

# Convert to base64url-safe string (URL-safe variant of base64)
# This creates a 43-character key (similar to production keys)
$apiKey = [Convert]::ToBase64String($bytes) -replace '\+', '-' -replace '/', '_' -replace '=', ''

# Alternative: Generate hex string (64 characters)
# $apiKey = ($bytes | ForEach-Object { $_.ToString("x2") }) -join ''

Write-Host "✅ API key generated successfully" -ForegroundColor Green
Write-Host "   Length: $($apiKey.Length) characters" -ForegroundColor Gray
Write-Host "   Format: Base64url (URL-safe)" -ForegroundColor Gray

# Write API key to file
try {
    $apiKey | Out-File -FilePath $apiKeyFile -Encoding UTF8 -NoNewline -Force
    Write-Host "`n📄 API key saved to: $apiKeyFile" -ForegroundColor Green
    
    # Set file permissions (Windows: remove inheritance, grant only current user)
    # On Windows, we'll use icacls to restrict access
    try {
        $currentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
        icacls $apiKeyFile /inheritance:r /grant "${currentUser}:F" | Out-Null
        Write-Host "🔒 File permissions set (restricted to current user)" -ForegroundColor Green
    } catch {
        Write-Host "⚠️  Could not set file permissions: $_" -ForegroundColor Yellow
        Write-Host "   Please manually restrict access to this file" -ForegroundColor Yellow
    }
    
} catch {
    Write-Host "❌ Failed to write API key: $_" -ForegroundColor Red
    exit 1
}

# Display first and last few characters for verification (don't show full key)
$preview = $apiKey.Substring(0, 8) + "..." + $apiKey.Substring($apiKey.Length - 8)
Write-Host "`n📋 API Key Preview: $preview" -ForegroundColor Cyan
Write-Host "   (Full key stored in: $apiKeyFile)" -ForegroundColor Gray

# Optionally update frontend .env file
if ($UpdateFrontend) {
    $frontendEnvFile = Join-Path $projectRoot "frontend" ".env"
    $frontendDir = Join-Path $projectRoot "frontend"
    
    if (Test-Path $frontendDir) {
        Write-Host "`n🔄 Updating frontend .env file..." -ForegroundColor Gray
        
        $envContent = @"
# Frontend Environment Variables
# Auto-generated by generate_api_key.ps1

# API Configuration
VITE_API_URL=http://localhost:8000

# API Key - Loaded from .ssh/dbt-dental-clinic-api-key.pem
VITE_API_KEY=$apiKey
"@
        
        try {
            Set-Content -Path $frontendEnvFile -Value $envContent -Force
            Write-Host "✅ Updated frontend .env file" -ForegroundColor Green
            Write-Host "   Location: $frontendEnvFile" -ForegroundColor Gray
        } catch {
            Write-Host "⚠️  Could not update frontend .env: $_" -ForegroundColor Yellow
        }
    } else {
        Write-Host "⚠️  Frontend directory not found, skipping .env update" -ForegroundColor Yellow
    }
}

Write-Host "`n✅ Local development API key generation complete!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "`n📝 Next Steps (LOCAL DEVELOPMENT):" -ForegroundColor Yellow
Write-Host "   1. API will automatically load key from: $apiKeyFile" -ForegroundColor Gray
if (-not $UpdateFrontend) {
    Write-Host "   2. Update frontend .env with: VITE_API_KEY=$apiKey" -ForegroundColor Gray
    Write-Host "      Or run: .\generate_api_key.ps1 -UpdateFrontend" -ForegroundColor Gray
}
Write-Host "   3. Restart API server to load new key" -ForegroundColor Gray
Write-Host "   4. Restart frontend dev server if updated" -ForegroundColor Gray
Write-Host ""
Write-Host "⚠️  REMINDER: This key is for LOCAL DEVELOPMENT ONLY" -ForegroundColor Yellow
Write-Host "   Production uses: deployment_credentials.json → api_key" -ForegroundColor Gray
Write-Host ""

