"""Frontend dev and status commands (Phase 5.3 / split Phase 4)."""

from __future__ import annotations

import json
import os
from typing import Optional
from urllib.error import URLError
from urllib.request import urlopen

import typer

from mdc_cli.credentials import (
    clinic_frontend_status,
    demo_frontend_status,
    read_local_api_key_from_pem,
)
from mdc_cli.deploy_frontend import (
    FRONTEND_APP_BY_TARGET,
    FRONTEND_WORKSPACE_BY_TARGET,
    read_last_deploy_record,
)
from mdc_cli.paths import FRONTEND_DIR, REPO_ROOT
from mdc_cli.process_util import find_executable, run_subprocess

frontend_app = typer.Typer(help="Local frontend development and status")

_APP_CHOICES = ("portfolio", "clinic")
_APP_TO_WORKSPACE = {
    "portfolio": "@mdc/portfolio",
    "clinic": "@mdc/clinic",
}


def _run_forever(cmd: list[str], *, cwd: str, env: dict[str, str] | None = None) -> int:
    return run_subprocess(cmd, cwd=cwd, env=env)


def _portal_ready(api_base: str) -> bool:
    try:
        with urlopen(f"{api_base}/auth/configured", timeout=2.0) as response:
            if response.status != 200:
                return False
            payload = json.loads(response.read().decode("utf-8"))
    except (URLError, TimeoutError, ValueError, json.JSONDecodeError):
        return False
    return bool(payload.get("portal_login_enabled"))


@frontend_app.command("dev")
def frontend_dev(
    app: Optional[str] = typer.Option(
        "portfolio",
        "--app",
        help="Which frontend app to run: portfolio (demo) or clinic",
    ),
) -> None:
    """Start Vite dev server for local API (localhost:8000)."""
    if app not in _APP_CHOICES:
        typer.echo(f"Invalid --app {app!r}. Choose: {', '.join(_APP_CHOICES)}", err=True)
        raise typer.Exit(code=2)

    if not FRONTEND_DIR.is_dir():
        typer.echo(f"Frontend directory not found: {FRONTEND_DIR}", err=True)
        raise typer.Exit(code=1)
    if not (FRONTEND_DIR / "package.json").is_file():
        typer.echo("No package.json in frontend directory.", err=True)
        raise typer.Exit(code=1)
    if find_executable("npm") is None:
        typer.echo("npm not found. Install Node.js.", err=True)
        raise typer.Exit(code=127)

    app_dir = FRONTEND_DIR / "apps" / app
    if not (app_dir / "package.json").is_file():
        typer.echo(f"App package not found: {app_dir}", err=True)
        raise typer.Exit(code=1)

    env_local = app_dir / ".env.local"
    api_key = read_local_api_key_from_pem()
    is_demo = app == "portfolio"
    lines = [
        "# Frontend Local Development Environment",
        f"# Auto-generated by mdc frontend dev --app {app}",
        "# LOCAL development only (opendental_analytics on localhost)",
        "",
        "VITE_API_URL=http://localhost:8000",
        f"VITE_IS_DEMO={'true' if is_demo else 'false'}",
    ]
    if api_key:
        lines.append(f"VITE_API_KEY={api_key}")
        typer.echo("API key loaded from .ssh/dbt-dental-clinic-api-key.pem")
    else:
        typer.echo(
            "API key file not found at .ssh/dbt-dental-clinic-api-key.pem - "
            "API requests may return 401.",
            err=True,
        )

    # Writes local gitignored .env.local for Vite (API key from local PEM).
    env_local.write_text("\n".join(lines) + "\n", encoding="utf-8")
    typer.echo(f"Created/updated {env_local.relative_to(REPO_ROOT)}")

    if not (FRONTEND_DIR / "node_modules").is_dir():
        typer.echo("Installing frontend dependencies...")
        code = _run_forever(["npm", "install"], cwd=str(FRONTEND_DIR))
        if code != 0:
            raise typer.Exit(code=code)

    workspace = _APP_TO_WORKSPACE[app]
    # Sanity: workspace map aligns with deploy targets.
    assert workspace in FRONTEND_WORKSPACE_BY_TARGET.values()

    typer.echo(f"Starting Vite ({workspace}) at http://localhost:3000")
    typer.echo("API URL: http://localhost:8000")
    if is_demo:
        typer.echo("Product: portfolio (no clinic auth env required)")
    else:
        typer.echo("Product: clinic portal (login required against local API)")
    child_env = os.environ.copy()
    if not is_demo and not child_env.get("MDC_API_PROXY_TARGET"):
        default_target = "http://127.0.0.1:8000"
        fallback_target = "http://127.0.0.1:8001"
        if not _portal_ready(default_target) and _portal_ready(fallback_target):
            child_env["MDC_API_PROXY_TARGET"] = fallback_target
    proxy_target = child_env.get("MDC_API_PROXY_TARGET", "http://127.0.0.1:8000")
    typer.echo(f"Proxy target: {proxy_target}")
    code = _run_forever(
        ["npm", "run", "dev", "-w", workspace],
        cwd=str(FRONTEND_DIR),
        env=child_env,
    )
    raise typer.Exit(code=code)


@frontend_app.command("status")
def frontend_status() -> None:
    """Show demo/clinic frontend apps, buckets, and last local deploy hint."""
    typer.echo("Frontend deployment status")
    typer.echo(
        "Nomenclature: --app portfolio|clinic (Vite apps); "
        "env stages demo|clinic; frontend deploy accepts demo|portfolio|clinic"
    )
    typer.echo("Apps: @mdc/portfolio (demo stage) · @mdc/clinic (clinic)")
    typer.echo("Dev:  mdc frontend dev --app portfolio|clinic")
    typer.echo("Deploy: mdc deploy frontend --target demo|portfolio|clinic")

    typer.echo("")
    typer.echo("Local workspace apps")
    for app_name, workspace in (
        ("portfolio", "@mdc/portfolio"),
        ("clinic", "@mdc/clinic"),
    ):
        app_dir = FRONTEND_DIR / "apps" / app_name
        present = (app_dir / "package.json").is_file()
        typer.echo(
            f"  {workspace}: {'ok' if present else 'MISSING'} "
            f"({app_dir.relative_to(REPO_ROOT) if present else app_dir})"
        )

    status_by_target = {
        "demo": demo_frontend_status(),
        "clinic": clinic_frontend_status(),
    }
    for target, status in status_by_target.items():
        workspace = FRONTEND_WORKSPACE_BY_TARGET[target]
        app_name = FRONTEND_APP_BY_TARGET[target]
        typer.echo("")
        typer.echo(f"{status.label}  [{workspace} / apps/{app_name}]")
        typer.echo(
            f"  S3 bucket: {status.bucket_name or 'not configured'}"
        )
        typer.echo(
            f"  CloudFront: {status.distribution_id or 'not configured'}"
        )
        typer.echo(f"  Domain: {status.domain or 'not configured'}")
        if status.api_url:
            typer.echo(f"  API URL: {status.api_url}")
        if status.api_key_source:
            typer.echo(f"  API key: from {status.api_key_source}")
        else:
            typer.echo("  API key: not configured")

        last = read_last_deploy_record(FRONTEND_DIR, target)
        if last:
            typer.echo(
                f"  Last local deploy: {last.get('deployed_at', 'unknown')} "
                f"(workspace={last.get('workspace')}, api={last.get('api_url')})"
            )
        else:
            typer.echo("  Last local deploy: none recorded")

    typer.echo("")
    prereqs = []
    for tool in ("aws", "node", "npm"):
        prereqs.append(f"  {tool}: {'ok' if find_executable(tool) else 'missing'}")
    typer.echo("Prerequisites:")
    for line in prereqs:
        typer.echo(line)
