"""Frontend dev and status commands (Phase 5.3)."""

from __future__ import annotations

import os

import typer

from mdc_cli.credentials import (
    clinic_frontend_status,
    demo_frontend_status,
    read_local_api_key_from_pem,
)
from mdc_cli.paths import FRONTEND_DIR, REPO_ROOT
from mdc_cli.process_util import find_executable, run_subprocess

frontend_app = typer.Typer(help="Local frontend development and status")


def _run_forever(cmd: list[str], *, cwd: str, env: dict[str, str] | None = None) -> int:
    return run_subprocess(cmd, cwd=cwd, env=env)


@frontend_app.command("dev")
def frontend_dev() -> None:
    """Start Vite dev server for local API (localhost:8000)."""
    if not FRONTEND_DIR.is_dir():
        typer.echo(f"Frontend directory not found: {FRONTEND_DIR}", err=True)
        raise typer.Exit(code=1)
    if not (FRONTEND_DIR / "package.json").is_file():
        typer.echo("No package.json in frontend directory.", err=True)
        raise typer.Exit(code=1)
    if find_executable("npm") is None:
        typer.echo("npm not found. Install Node.js.", err=True)
        raise typer.Exit(code=127)

    env_local = FRONTEND_DIR / ".env.local"
    api_key = read_local_api_key_from_pem()
    lines = [
        "# Frontend Local Development Environment",
        "# Auto-generated by mdc frontend dev",
        "# LOCAL development only (opendental_analytics on localhost)",
        "",
        "VITE_API_URL=http://localhost:8000",
    ]
    if api_key:
        lines.append(f"VITE_API_KEY={api_key}")
        typer.echo("API key loaded from .ssh/dbt-dental-clinic-api-key.pem")
    else:
        typer.echo(
            "API key file not found at .ssh/dbt-dental-clinic-api-key.pem - "
            "API requests may return 401.",
            err=True,
        )

    env_local.write_text("\n".join(lines) + "\n", encoding="utf-8")
    typer.echo(f"Created/updated {env_local.relative_to(REPO_ROOT)}")

    if not (FRONTEND_DIR / "node_modules").is_dir():
        typer.echo("Installing frontend dependencies...")
        code = _run_forever(["npm", "install"], cwd=str(FRONTEND_DIR))
        if code != 0:
            raise typer.Exit(code=code)

    typer.echo("Starting Vite dev server at http://localhost:3000")
    typer.echo("API URL: http://localhost:8000")
    code = _run_forever(["npm", "run", "dev"], cwd=str(FRONTEND_DIR), env=os.environ.copy())
    raise typer.Exit(code=code)


@frontend_app.command("status")
def frontend_status() -> None:
    """Show demo/clinic frontend deploy configuration."""
    typer.echo("Frontend deployment status")
    typer.echo(
        "Nomenclature: local = localhost dev | demo = portfolio | clinic = production"
    )

    for status in (demo_frontend_status(), clinic_frontend_status()):
        typer.echo("")
        typer.echo(status.label)
        typer.echo(
            f"  S3 bucket: {status.bucket_name or 'not configured'}"
        )
        typer.echo(
            f"  CloudFront: {status.distribution_id or 'not configured'}"
        )
        typer.echo(f"  Domain: {status.domain or 'not configured'}")
        if status.api_url:
            typer.echo(f"  API URL: {status.api_url}")
        if status.api_key_source:
            typer.echo(f"  API key: from {status.api_key_source}")
        else:
            typer.echo("  API key: not configured")

    typer.echo("")
    prereqs = []
    for tool in ("aws", "node", "npm"):
        prereqs.append(f"  {tool}: {'ok' if find_executable(tool) else 'missing'}")
    typer.echo("Prerequisites:")
    for line in prereqs:
        typer.echo(line)
